Fixed a bug where the classloader field of the type factory of the object mapper was null, causing the wrong context classloader to be used, resulting in NoClassDefFoundError